### ISSUE TITLE
CORS with netlify

### ISSUE THREAD

**Issue by spamntaters** [ThomasW0221/foodbank-api#16]
The CORS settings currently do not allow for the frontend on Netlify to access the backend on heroku

**Comment by ThomasW0221** [comment]
Yeah, I saw earlier today that cors config is only configured for localhost on default angular port. I will add actually address probably tomorrow cuz I will be afk for most of tonight

**Comment by ThomasW0221** [comment]
Actually Craig could make the changes as well.

**Comment by ThomasW0221** [comment]
@spamntaters added it to the cors config, so I will close this issue. let me konw/reopen the issue if there is still a problem
