### ISSUE TITLE
Stats page doesn't work in production?

### ISSUE THREAD

**Issue by spamntaters** [ThomasW0221/foodbank-api#59]
![](file:///Users/Sam/Desktop/Screen%20Shot%202019-12-08%20at%207.42.55%20PM.png)

**Comment by spamntaters** [comment]
![image](https://user-images.githubusercontent.com/10841651/70399583-5ad6df00-19f3-11ea-9bae-320e46593add.png)

**Comment by TimTam950** [comment]
Did it work on the develop branch?

**Comment by spamntaters** [comment]
@ThomasW0221 master works locally

**Comment by TimTam950** [comment]
I think this is actually a front-end issue. I think I wrote the root url for the stats stuff with http instead of https and that is causing it.
